version: '3.9'
services:
# docker-compose up -d neo4j-graph-db
  neo4j-graph-db:
    image: neo4j:5
    container_name: neo4j-graph-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./.data/neo4j/data:/data
      - ./.data/neo4j/logs:/logs
      - ./.data/neo4j/import:/var/lib/neo4j/import
      - ./.data/neo4j/plugins:/plugins
      - ./.data/neo4j/conf:/conf
      - ./.data/neo4j/conf:/var/lib/neo4j/config
    networks:
      - netlib-network

networks:
  netlib-network:
    driver: bridge
